### ISSUE TITLE
Testing Keywords in PP, in preparation of the crawl

### ISSUE THREAD

**Issue by dadak-dom** [privacy-tech-lab/privacy-pioneer-web-crawler#12]
As discussed in our last meeting, we need to find a way to make check that keywords (especially email) can be triggered in PP. First, we'll check to see if they work normally in PP before trying to automate them in a crawl.

**Comment by SebastianZimmeck** [comment]
As background info for email address keywords, here is an [NY Times article](https://web.archive.org/web/20231216120053/https://www.nytimes.com/2023/01/25/technology/personaltech/email-address-digital-tracking.html) on the use of email addresses as ad identifier. Maybe, there is a way to trigger the Trade Desk integrated on sites (not sure; longshot). Also, [EFF After Cookies, Ad Tech Wants to Use Your Email to Track You Everywhere](https://www.eff.org/deeplinks/2021/04/after-cookies-ad-tech-wants-use-your-email-track-you-everywhere).

**Comment by JoeChampeau** [comment]
I've added in functionality for automatically clicking through the Google sign-in popup that'll appear for sites that integrate sign-in via Google. It seems to trigger a first party request with the email contained in it like we expect, but further testing is needed to make sure this is working properly.

Furthermore:
1. Currently, the login doesn't seem to proceed unless the page is refreshed after the prompt is closed. We should make sure to account for duplicate data if refreshing remains necessary. Also, one of the pages, realtor.com, threw a bot detection error page after a refresh, so that could be an issue.
2. We should consider how this will affect the crawler's timeout duration. Should we wait for the whole duration initially prescribed before attempting to login, and then wait the same duration again after login? Should it be split? (i.e. 22 seconds in total, with sites checking halfway through if a Google login notification has loaded, logging in if necessary, and then waiting the other half?

**Comment by SebastianZimmeck** [comment]
Excellent work, @JoeChampeau! Let's discuss the points you raise today.
